// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WorldqlFb.Messages
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Entity : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_2_0_0(); }
  public static Entity GetRootAsEntity(ByteBuffer _bb) { return GetRootAsEntity(_bb, new Entity()); }
  public static Entity GetRootAsEntity(ByteBuffer _bb, Entity obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Entity __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Uuid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUuidBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetUuidBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetUuidArray() { return __p.__vector_as_array<byte>(4); }
  public WorldqlFb.Messages.Vec3d? Position { get { int o = __p.__offset(6); return o != 0 ? (WorldqlFb.Messages.Vec3d?)(new WorldqlFb.Messages.Vec3d()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public string WorldName { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetWorldNameBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetWorldNameBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetWorldNameArray() { return __p.__vector_as_array<byte>(8); }
  public string Data { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetDataArray() { return __p.__vector_as_array<byte>(10); }
  public byte Flex(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int FlexLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFlexBytes() { return __p.__vector_as_span<byte>(12, 1); }
#else
  public ArraySegment<byte>? GetFlexBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public byte[] GetFlexArray() { return __p.__vector_as_array<byte>(12); }

  public static Offset<WorldqlFb.Messages.Entity> CreateEntity(FlatBufferBuilder builder,
      StringOffset uuidOffset = default(StringOffset),
      WorldqlFb.Messages.Vec3dT position = null,
      StringOffset world_nameOffset = default(StringOffset),
      StringOffset dataOffset = default(StringOffset),
      VectorOffset flexOffset = default(VectorOffset)) {
    builder.StartTable(5);
    Entity.AddFlex(builder, flexOffset);
    Entity.AddData(builder, dataOffset);
    Entity.AddWorldName(builder, world_nameOffset);
    Entity.AddPosition(builder, WorldqlFb.Messages.Vec3d.Pack(builder, position));
    Entity.AddUuid(builder, uuidOffset);
    return Entity.EndEntity(builder);
  }

  public static void StartEntity(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddUuid(FlatBufferBuilder builder, StringOffset uuidOffset) { builder.AddOffset(0, uuidOffset.Value, 0); }
  public static void AddPosition(FlatBufferBuilder builder, Offset<WorldqlFb.Messages.Vec3d> positionOffset) { builder.AddStruct(1, positionOffset.Value, 0); }
  public static void AddWorldName(FlatBufferBuilder builder, StringOffset worldNameOffset) { builder.AddOffset(2, worldNameOffset.Value, 0); }
  public static void AddData(FlatBufferBuilder builder, StringOffset dataOffset) { builder.AddOffset(3, dataOffset.Value, 0); }
  public static void AddFlex(FlatBufferBuilder builder, VectorOffset flexOffset) { builder.AddOffset(4, flexOffset.Value, 0); }
  public static VectorOffset CreateFlexVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateFlexVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static void StartFlexVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<WorldqlFb.Messages.Entity> EndEntity(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<WorldqlFb.Messages.Entity>(o);
  }
  public EntityT UnPack() {
    var _o = new EntityT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(EntityT _o) {
    _o.Uuid = this.Uuid;
    _o.Position = this.Position.HasValue ? this.Position.Value.UnPack() : null;
    _o.WorldName = this.WorldName;
    _o.Data = this.Data;
    _o.Flex = new List<byte>();
    for (var _j = 0; _j < this.FlexLength; ++_j) {_o.Flex.Add(this.Flex(_j));}
  }
  public static Offset<WorldqlFb.Messages.Entity> Pack(FlatBufferBuilder builder, EntityT _o) {
    if (_o == null) return default(Offset<WorldqlFb.Messages.Entity>);
    var _uuid = _o.Uuid == null ? default(StringOffset) : builder.CreateString(_o.Uuid);
    var _world_name = _o.WorldName == null ? default(StringOffset) : builder.CreateString(_o.WorldName);
    var _data = _o.Data == null ? default(StringOffset) : builder.CreateString(_o.Data);
    var _flex = default(VectorOffset);
    if (_o.Flex != null) {
      var __flex = _o.Flex.ToArray();
      _flex = CreateFlexVector(builder, __flex);
    }
    return CreateEntity(
      builder,
      _uuid,
      _o.Position,
      _world_name,
      _data,
      _flex);
  }
}

public class EntityT
{
  public string Uuid { get; set; }
  public WorldqlFb.Messages.Vec3dT Position { get; set; }
  public string WorldName { get; set; }
  public string Data { get; set; }
  public List<byte> Flex { get; set; }

  public EntityT() {
    this.Uuid = null;
    this.Position = new WorldqlFb.Messages.Vec3dT();
    this.WorldName = null;
    this.Data = null;
    this.Flex = null;
  }
}


}
