// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace WorldqlFb.Messages
{

public enum Replication : byte
{
  ExceptSelf = 0,
  IncludingSelf = 1,
  OnlySelf = 2,
};


}
